-- SUPABASE SQL SCHEMA FOR CODELUXE PORTFOLIO

-- 1. Create table for contact submissions / quotes
CREATE TABLE IF NOT EXISTS public.quotes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,                       -- Client phone number with country code
    subject TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration query if table already exists:
-- ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS phone TEXT;

-- Enable RLS (Row Level Security)
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (so website visitors can submit the contact form)
CREATE POLICY "Allow anon insert to quotes" 
ON public.quotes 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Allow authenticated users (you) to select/read the quotes
CREATE POLICY "Allow authenticated select from quotes" 
ON public.quotes 
FOR SELECT 
TO authenticated 
USING (true);


-- 2. Create table for recent works
CREATE TABLE IF NOT EXISTS public.recent_works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    video_url TEXT NOT NULL,          -- Supabase Storage video public link
    card_image_url TEXT,              -- Fallback preview card image link
    project_url TEXT,                 -- URL to redirect user to live website
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration query if table already exists (run in SQL Editor):
-- ALTER TABLE public.recent_works ADD COLUMN IF NOT EXISTS project_url TEXT;

-- Enable RLS
ALTER TABLE public.recent_works ENABLE ROW LEVEL SECURITY;

-- Allow anonymous select (so website visitors can view your portfolio videos)
CREATE POLICY "Allow anon select from recent_works" 
ON public.recent_works 
FOR SELECT 
TO anon 
USING (true);

-- Allow authenticated users to perform all CRUD operations
CREATE POLICY "Allow authenticated CRUD on recent_works" 
ON public.recent_works 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
