-- SUPABASE SQL SCHEMA FOR CODELUXE PORTFOLIO

-- 1. Create table for contact submissions / quotes
CREATE TABLE IF NOT EXISTS public.quotes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,                       -- Client phone number with country code
    subject TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration query if table already exists:
-- ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS phone TEXT;

-- Enable RLS (Row Level Security)
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (so website visitors can submit the contact form)
CREATE POLICY "Allow anon insert to quotes" 
ON public.quotes 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Allow authenticated users (you) to select/read the quotes
CREATE POLICY "Allow authenticated select from quotes" 
ON public.quotes 
FOR SELECT 
TO authenticated 
USING (true);


-- 2. Create table for recent works
CREATE TABLE IF NOT EXISTS public.recent_works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    video_url TEXT NOT NULL,          -- Supabase Storage video public link
    card_image_url TEXT,              -- Fallback preview card image link
    project_url TEXT,                 -- URL to redirect user to live website
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safe indexes for optimized sorting
CREATE INDEX IF NOT EXISTS recent_works_created_at_idx ON public.recent_works (created_at DESC);
CREATE INDEX IF NOT EXISTS recent_works_id_idx ON public.recent_works (id ASC);

-- Enable RLS
ALTER TABLE public.recent_works ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid duplication errors
DROP POLICY IF EXISTS "Allow anon select from recent_works" ON public.recent_works;
DROP POLICY IF EXISTS "Allow authenticated CRUD on recent_works" ON public.recent_works;
DROP POLICY IF EXISTS "Allow authenticated insert on recent_works" ON public.recent_works;
DROP POLICY IF EXISTS "Allow authenticated update on recent_works" ON public.recent_works;
DROP POLICY IF EXISTS "Allow authenticated delete on recent_works" ON public.recent_works;

-- Allow anonymous select (so website visitors can view your portfolio cards and videos)
CREATE POLICY "Allow anon select from recent_works" 
ON public.recent_works 
FOR SELECT 
TO anon 
USING (true);

-- Allow authenticated users to perform all CRUD operations (safe database management)
CREATE POLICY "Allow authenticated CRUD on recent_works" 
ON public.recent_works 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- 3. Storage Bucket Documentation & Migration Guidelines
--
-- Go to your Supabase Console -> Storage -> Buckets.
-- Create a new PUBLIC bucket named: recent_works
--
-- Inside the bucket, you can organize your assets using folders:
--   recent_works/
--     images/   -- Place preview card images here
--     videos/   -- Place MP4 demo walkthrough videos here
--
-- Copy the Public URLs of the uploaded assets and insert them into the recent_works table:
--
-- Example SQL Insert:
-- INSERT INTO public.recent_works (title, description, card_image_url, video_url, project_url)
-- VALUES (
--   'My Premium App',
--   'Full description of the project detailing modern UI and performance optimization.',
--   'https://[your-project-id].supabase.co/storage/v1/object/public/recent_works/images/project-cover.png',
--   'https://[your-project-id].supabase.co/storage/v1/object/public/recent_works/videos/project-demo.mp4',
--   'https://my-live-project.com'
-- 4. Create table for client reviews (testimonials)
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,                        -- Reviewer's name (e.g. 'Jane Doe')
    company TEXT NOT NULL,            -- e.g. 'Future Enterprise'
    title TEXT,                       -- e.g. 'Product Director'
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5), -- 1 to 5 stars
    quote TEXT NOT NULL,              -- Full commentary
    avatar_url TEXT,                  -- Optional profile picture public URL
    date TEXT,                        -- Optional project badge/date (e.g. 'Next Project')
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Migration query if table already exists:
-- ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS name TEXT;
-- ALTER TABLE public.reviews ADD COLUMN IF NOT EXISTS avatar_url TEXT;
-- ALTER TABLE public.reviews ALTER COLUMN title DROP NOT NULL;

-- Safe indexes for reviews ordering
CREATE INDEX IF NOT EXISTS reviews_id_idx ON public.reviews (id ASC);

-- Enable RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid duplication errors
DROP POLICY IF EXISTS "Allow anon select from reviews" ON public.reviews;
DROP POLICY IF EXISTS "Allow authenticated CRUD on reviews" ON public.reviews;

-- Allow anonymous select (so website visitors can read reviews)
CREATE POLICY "Allow anon select from reviews" 
ON public.reviews 
FOR SELECT 
TO anon 
USING (true);

-- Allow authenticated users to perform all CRUD operations (safe database management)
CREATE POLICY "Allow authenticated CRUD on reviews" 
ON public.reviews 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Example SQL Insert for reviews:
-- INSERT INTO public.reviews (name, company, title, rating, quote, avatar_url, date)
-- VALUES (
--   'Sarah Jenkins',
--   'Future Enterprise',
--   'Product Director',
--   5,
--   'Partner with abcdwebsite to transform your ideas into luxury digital architectures. The performance and visuals are unmatched.',
--   'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop',
--   'Next Project'
-- );
